apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: {{ required "Please supply mesh.name value" .Values.mesh.name }}
spec:
  namespaceSelector:
    matchLabels:
      mesh: {{ .Values.mesh.name }}