# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: {{ required "Please supply mesh.name value" .Values.appMesh.name }}
spec:
  namespaceSelector:
    matchLabels:
      mesh: {{ .Values.appMesh.name }}