# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

apiVersion: v1
kind: Service
metadata:
  name: {{ template "eks-app-mesh-gateway.fullname" . }}
  labels:
    app: {{ template "eks-app-mesh-gateway.name" . }}
    chart: {{ template "eks-app-mesh-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{- if not .Values.ingress.alb }}
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
{{- end }}
spec:
{{- if .Values.ingress.alb }}
  type: ClusterIP
{{- else }}
  type: LoadBalancer
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.containerPort }}
      name: http
  selector:
    app: {{ template "eks-app-mesh-gateway.name" . }}
    release: {{ .Release.Name }}
