# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# Default values for eks-app-mesh-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# fullnameOverride: eks-app-mesh-gateway
replicaCount: 1

image:
  awsRegion:
  tag: v1.16.1.1-prod # Latest version info is at https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy.html
  pullPolicy: IfNotPresent
imagePullSecrets: []
  # Optionally specify an array of imagePullSecrets.
  # Secrets must be manually created in the namespace.
  # ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
  #
  # This uses credentials from secret "myRegistryKeySecretName".
  # - name: myRegistryKeySecretName
service:
  port: 80

deployment:
  containerPort: 8088

probes:
  enabled: false

appMesh:
  fargatePodServiceAccount: # envoy-fargate-pod-svcaccount # Specify when running on EKS Fargate nodes

ingress:
  enabled: true # when set to true, a LB will be created to let the traffic into the mesh
  alb: false # if true, ALB Ingress Contoller needs to be pre-installed. If false, NLB will be used. Fargate supports ALB only for now.
  annotations:
    # kubernetes.io/tls-acme: "true"
    # alb.ingress.kubernetes.io/group.name: eks-reusable-ingress # Uncomment or override this value to share single ALB for multiple Ingress resources
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

  path: /*
  # hosts:
  #   - chart-example.local
  tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
secrets: {}
  # Optionally specify a set of secret objects whose values
  # will be injected as environment variables by default.
  # You should add this section to a file like secrets.yaml
  # that is explicitly NOT committed to source code control
  # and then include it as part of your helm install step.
  # ref: https://kubernetes.io/docs/concepts/configuration/secret/
  #
  # This creates a secret "mysecret" and injects "mypassword"
  # as the environment variable mysecret_mypassword=password.
  # mysecret:
  #   mypassword: password
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
nodeSelector: {}

tolerations: []

affinity: {}